/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Classes.Program;
import Classes.Status;
import Classes.Appointment;
import Classes.People;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class People_menu extends javax.swing.JFrame {

    /**
     * Creates new form Vaccination_appointment
     */
    boolean isFound = false;
    
    public People_menu() {
        
        setTitle("Vaccination Appointment");
        initComponents();
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rvpRegister1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelLogoutMenuBar = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        rvpid = new javax.swing.JTextField();
        rvpname = new javax.swing.JTextField();
        rvpphoneNumber = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        rvpemail = new javax.swing.JTextField();
        btn_rvpRegister = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        mvpID = new javax.swing.JTextField();
        mvpName = new javax.swing.JTextField();
        mvpPhoneNumber = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        mvpEmail = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        btn_mvpConfirm = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        btn_vvpView = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        vvpEmail = new javax.swing.JTextField();
        vvpName = new javax.swing.JTextField();
        vvpPhoneNumber = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        vvpID = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        btn_rvaSubmit = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        rvaid = new javax.swing.JTextField();
        rvaname = new javax.swing.JTextField();
        rvadate = new javax.swing.JTextField();
        rvaphoneNumber = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rvavaccine = new javax.swing.JComboBox<>();
        rvacentre = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        cvaID = new javax.swing.JTextField();
        btn_cvaConfirm = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btn_vvaView = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        vvaID = new javax.swing.JTextField();
        vvaCentre = new javax.swing.JTextField();
        vvaName = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        vvaPhoneNumber = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        vvaDate = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        vvaVaccine = new javax.swing.JTextField();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        vvsID = new javax.swing.JTextField();
        vvsName = new javax.swing.JTextField();
        vvsCitizen = new javax.swing.JTextField();
        vvsStatus = new javax.swing.JTextField();
        btn_vvsConfirm = new javax.swing.JButton();
        vvsDate = new javax.swing.JTextField();

        rvpRegister1.setBackground(new java.awt.Color(51, 255, 255));
        rvpRegister1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        rvpRegister1.setForeground(new java.awt.Color(0, 0, 0));
        rvpRegister1.setText("Register");
        rvpRegister1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rvpRegister1ActionPerformed(evt);
            }
        });

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("People Menu");

        jLabelLogoutMenuBar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelLogoutMenuBar.setForeground(new java.awt.Color(0, 0, 0));
        jLabelLogoutMenuBar.setText("Logout");
        jLabelLogoutMenuBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLogoutMenuBarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelLogoutMenuBar)
                .addGap(26, 26, 26))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelLogoutMenuBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane2.setBackground(new java.awt.Color(51, 255, 255));
        jTabbedPane2.setForeground(new java.awt.Color(0, 0, 0));

        jTabbedPane3.setBackground(new java.awt.Color(102, 255, 255));
        jTabbedPane3.setForeground(new java.awt.Color(0, 0, 0));

        jPanel6.setBackground(new java.awt.Color(153, 255, 255));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Enter ID:");

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Enter Name:");

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Enter Phone Number:");

        rvpid.setBackground(new java.awt.Color(255, 255, 255));
        rvpid.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        rvpid.setForeground(new java.awt.Color(0, 0, 0));

        rvpname.setBackground(new java.awt.Color(255, 255, 255));
        rvpname.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        rvpname.setForeground(new java.awt.Color(0, 0, 0));

        rvpphoneNumber.setBackground(new java.awt.Color(255, 255, 255));
        rvpphoneNumber.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        rvpphoneNumber.setForeground(new java.awt.Color(0, 0, 0));

        jLabel38.setBackground(new java.awt.Color(0, 0, 0));
        jLabel38.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 0, 0));
        jLabel38.setText("Enter Email:");

        rvpemail.setBackground(new java.awt.Color(255, 255, 255));
        rvpemail.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        rvpemail.setForeground(new java.awt.Color(0, 0, 0));

        btn_rvpRegister.setBackground(new java.awt.Color(51, 255, 255));
        btn_rvpRegister.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_rvpRegister.setForeground(new java.awt.Color(0, 0, 0));
        btn_rvpRegister.setText("Register");
        btn_rvpRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rvpRegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel38)
                                    .addComponent(rvpemail, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rvpphoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(rvpname)
                                    .addComponent(jLabel9)
                                    .addComponent(rvpid, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(btn_rvpRegister)))
                .addContainerGap(227, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel8)
                .addGap(0, 0, 0)
                .addComponent(rvpid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rvpname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rvpphoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel38)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rvpemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(btn_rvpRegister)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Register", jPanel6);

        jPanel7.setBackground(new java.awt.Color(153, 255, 255));

        mvpID.setBackground(new java.awt.Color(255, 255, 255));
        mvpID.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        mvpID.setForeground(new java.awt.Color(0, 0, 0));

        mvpName.setBackground(new java.awt.Color(255, 255, 255));
        mvpName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        mvpName.setForeground(new java.awt.Color(0, 0, 0));

        mvpPhoneNumber.setBackground(new java.awt.Color(255, 255, 255));
        mvpPhoneNumber.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        mvpPhoneNumber.setForeground(new java.awt.Color(0, 0, 0));

        jLabel39.setBackground(new java.awt.Color(0, 0, 0));
        jLabel39.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 0, 0));
        jLabel39.setText("Enter New Email:");

        mvpEmail.setBackground(new java.awt.Color(255, 255, 255));
        mvpEmail.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        mvpEmail.setForeground(new java.awt.Color(0, 0, 0));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Enter Your ID:");

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Enter New Name:");

        jLabel40.setBackground(new java.awt.Color(0, 0, 0));
        jLabel40.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 0, 0));
        jLabel40.setText("Enter New Phone Number:");

        btn_mvpConfirm.setBackground(new java.awt.Color(51, 255, 255));
        btn_mvpConfirm.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_mvpConfirm.setForeground(new java.awt.Color(0, 0, 0));
        btn_mvpConfirm.setText("Confirm");
        btn_mvpConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mvpConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel39)
                            .addComponent(mvpEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mvpPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel40)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(mvpName)
                                .addComponent(jLabel11)
                                .addComponent(mvpID, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(332, 332, 332)
                        .addComponent(btn_mvpConfirm)))
                .addContainerGap(217, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mvpID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mvpName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel40)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mvpPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel39)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mvpEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btn_mvpConfirm)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Modify", jPanel7);

        jPanel8.setBackground(new java.awt.Color(153, 255, 255));

        btn_vvpView.setBackground(new java.awt.Color(51, 255, 255));
        btn_vvpView.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_vvpView.setForeground(new java.awt.Color(0, 0, 0));
        btn_vvpView.setText("View");
        btn_vvpView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vvpViewActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Phone Number:");

        vvpEmail.setBackground(new java.awt.Color(255, 255, 255));
        vvpEmail.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        vvpEmail.setForeground(new java.awt.Color(0, 0, 0));

        vvpName.setBackground(new java.awt.Color(255, 255, 255));
        vvpName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        vvpName.setForeground(new java.awt.Color(0, 0, 0));

        vvpPhoneNumber.setBackground(new java.awt.Color(255, 255, 255));
        vvpPhoneNumber.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        vvpPhoneNumber.setForeground(new java.awt.Color(0, 0, 0));

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Enter ID to view your program:");

        jLabel16.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Name:");

        jLabel17.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Email:");

        vvpID.setBackground(new java.awt.Color(255, 255, 255));
        vvpID.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        vvpID.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(vvpName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(vvpPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel17)
                            .addComponent(vvpEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vvpID, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(323, 323, 323)
                        .addComponent(btn_vvpView)))
                .addContainerGap(230, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vvpID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vvpName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vvpPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vvpEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(btn_vvpView)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("View", jPanel8);

        jTabbedPane2.addTab("Vaccination Program", jTabbedPane3);

        jTabbedPane1.setBackground(new java.awt.Color(102, 255, 255));
        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));

        btn_rvaSubmit.setBackground(new java.awt.Color(51, 255, 255));
        btn_rvaSubmit.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_rvaSubmit.setForeground(new java.awt.Color(0, 0, 0));
        btn_rvaSubmit.setText("Submit");
        btn_rvaSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rvaSubmitActionPerformed(evt);
            }
        });

        jTextArea2.setBackground(new java.awt.Color(102, 255, 255));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea2.setRows(5);
        jTextArea2.setText("Note:\nAppointment Date Format:\nDD/MM/YYYY\n");
        jScrollPane2.setViewportView(jTextArea2);

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Enter Phone Number:");

        rvaid.setBackground(new java.awt.Color(255, 255, 255));
        rvaid.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        rvaid.setForeground(new java.awt.Color(0, 0, 0));

        rvaname.setBackground(new java.awt.Color(255, 255, 255));
        rvaname.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        rvaname.setForeground(new java.awt.Color(0, 0, 0));

        rvadate.setBackground(new java.awt.Color(255, 255, 255));
        rvadate.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        rvadate.setForeground(new java.awt.Color(0, 0, 0));

        rvaphoneNumber.setBackground(new java.awt.Color(255, 255, 255));
        rvaphoneNumber.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        rvaphoneNumber.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Enter ID:");

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Enter Name:");

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Enter Appointment Date:");

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Enter Appointment Vaccine:");

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Enter Appointment Centre:");

        rvavaccine.setBackground(new java.awt.Color(255, 255, 255));
        rvavaccine.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        rvavaccine.setForeground(new java.awt.Color(0, 0, 0));
        rvavaccine.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Vaccine", "AstraZeneca", "Johnson&Johnson", "Pfizer" }));

        rvacentre.setBackground(new java.awt.Color(255, 255, 255));
        rvacentre.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        rvacentre.setForeground(new java.awt.Color(0, 0, 0));
        rvacentre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Centre", "Kuala Lumpur", "Selangor", "Penang", "Sabah", "Sarawak", "Negeri Sembilan", "Malacca" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(rvavaccine, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(rvadate)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(rvaphoneNumber)
                                    .addComponent(jLabel4)
                                    .addComponent(rvaname)
                                    .addComponent(jLabel3)
                                    .addComponent(rvaid)
                                    .addComponent(rvacentre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel2))))
                    .addComponent(btn_rvaSubmit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rvaid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rvaname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rvadate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(11, 11, 11)
                .addComponent(rvacentre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rvavaccine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rvaphoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btn_rvaSubmit)
                .addGap(37, 37, 37))
        );

        jTabbedPane1.addTab("Register", jPanel2);

        jPanel4.setBackground(new java.awt.Color(153, 255, 255));

        jLabel23.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("Enter Your ID to Cancel Appointment:");

        cvaID.setBackground(new java.awt.Color(255, 255, 255));
        cvaID.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        cvaID.setForeground(new java.awt.Color(0, 0, 0));

        btn_cvaConfirm.setBackground(new java.awt.Color(51, 255, 255));
        btn_cvaConfirm.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_cvaConfirm.setForeground(new java.awt.Color(0, 0, 0));
        btn_cvaConfirm.setText("Confirm");
        btn_cvaConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cvaConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(216, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cvaID, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(btn_cvaConfirm)))
                .addGap(209, 209, 209))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(185, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cvaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125)
                .addComponent(btn_cvaConfirm)
                .addGap(146, 146, 146))
        );

        jTabbedPane1.addTab("Cancel", jPanel4);

        jPanel5.setBackground(new java.awt.Color(153, 255, 255));

        btn_vvaView.setBackground(new java.awt.Color(51, 255, 255));
        btn_vvaView.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_vvaView.setForeground(new java.awt.Color(0, 0, 0));
        btn_vvaView.setText("View");
        btn_vvaView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vvaViewActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Enter ID to view your appointment:");

        vvaID.setBackground(new java.awt.Color(255, 255, 255));
        vvaID.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        vvaID.setForeground(new java.awt.Color(0, 0, 0));

        vvaCentre.setBackground(new java.awt.Color(255, 255, 255));
        vvaCentre.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        vvaCentre.setForeground(new java.awt.Color(0, 0, 0));

        vvaName.setBackground(new java.awt.Color(255, 255, 255));
        vvaName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        vvaName.setForeground(new java.awt.Color(0, 0, 0));

        jLabel18.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Phone Number:");

        vvaPhoneNumber.setBackground(new java.awt.Color(255, 255, 255));
        vvaPhoneNumber.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        vvaPhoneNumber.setForeground(new java.awt.Color(0, 0, 0));

        jLabel19.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("Name:");

        jLabel20.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Appointment Centre:");

        jLabel21.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("Appointment Date:");

        vvaDate.setBackground(new java.awt.Color(255, 255, 255));
        vvaDate.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        vvaDate.setForeground(new java.awt.Color(0, 0, 0));

        jLabel22.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("Appointment Vaccine:");

        vvaVaccine.setBackground(new java.awt.Color(255, 255, 255));
        vvaVaccine.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        vvaVaccine.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(vvaName, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(vvaVaccine, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(vvaPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel20)
                            .addComponent(vvaCentre, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel21)
                                .addComponent(vvaDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(vvaID, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel18)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(331, 331, 331)
                        .addComponent(btn_vvaView)))
                .addContainerGap(220, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(vvaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vvaName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vvaDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vvaCentre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vvaVaccine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vvaPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btn_vvaView)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("View", jPanel5);

        jTabbedPane2.addTab("Vaccination Appointment", jTabbedPane1);

        jTabbedPane4.setBackground(new java.awt.Color(102, 255, 255));
        jTabbedPane4.setForeground(new java.awt.Color(0, 0, 0));

        jPanel9.setBackground(new java.awt.Color(153, 255, 255));

        jLabel26.setBackground(new java.awt.Color(0, 0, 0));
        jLabel26.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("Enter ID to view your status:");

        jLabel27.setBackground(new java.awt.Color(0, 0, 0));
        jLabel27.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setText("Name:");

        jLabel28.setBackground(new java.awt.Color(0, 0, 0));
        jLabel28.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 0));
        jLabel28.setText("Citizen/Non-Citizen:");

        jLabel29.setBackground(new java.awt.Color(0, 0, 0));
        jLabel29.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(0, 0, 0));
        jLabel29.setText("Status:");

        jLabel30.setBackground(new java.awt.Color(0, 0, 0));
        jLabel30.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 0));
        jLabel30.setText("Vaccinated Date:");

        vvsID.setBackground(new java.awt.Color(255, 255, 255));
        vvsID.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        vvsID.setForeground(new java.awt.Color(0, 0, 0));

        vvsName.setBackground(new java.awt.Color(255, 255, 255));
        vvsName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        vvsName.setForeground(new java.awt.Color(0, 0, 0));

        vvsCitizen.setBackground(new java.awt.Color(255, 255, 255));
        vvsCitizen.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        vvsCitizen.setForeground(new java.awt.Color(0, 0, 0));

        vvsStatus.setBackground(new java.awt.Color(255, 255, 255));
        vvsStatus.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        vvsStatus.setForeground(new java.awt.Color(0, 0, 0));

        btn_vvsConfirm.setBackground(new java.awt.Color(51, 255, 255));
        btn_vvsConfirm.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_vvsConfirm.setForeground(new java.awt.Color(0, 0, 0));
        btn_vvsConfirm.setText("Confirm");
        btn_vvsConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vvsConfirmActionPerformed(evt);
            }
        });

        vvsDate.setBackground(new java.awt.Color(255, 255, 255));
        vvsDate.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        vvsDate.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(vvsCitizen)
                                .addComponent(jLabel30)
                                .addComponent(jLabel29)
                                .addComponent(vvsStatus)
                                .addComponent(jLabel28)
                                .addComponent(vvsName)
                                .addComponent(jLabel27)
                                .addComponent(vvsID, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(vvsDate, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel26)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addComponent(btn_vvsConfirm)))
                .addContainerGap(225, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel26)
                .addGap(0, 0, 0)
                .addComponent(vvsID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vvsName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vvsCitizen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vvsDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vvsStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(btn_vvsConfirm)
                .addGap(48, 48, 48))
        );

        jTabbedPane4.addTab("View&Search", jPanel9);

        jTabbedPane2.addTab("Vaccination Status", jTabbedPane4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_rvaSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rvaSubmitActionPerformed

        
        // get input from people
        String id = rvaid.getText().toString();
        String pname = rvaname.getText().toString();
        String date = rvadate.getText().toString();
        int centre = rvacentre.getSelectedIndex();
        int vacName = rvavaccine.getSelectedIndex();
        String phoneNumber = rvaphoneNumber.getText().toString();
        
        // if textfield is null show error message
        if(id.equals("")){
            JOptionPane.showMessageDialog(null,"ID is mandotory.");
        }
        if(pname.equals("")){
                JOptionPane.showMessageDialog(null,"Name is mandotory.");
            }
        if(date.equals("")){
                JOptionPane.showMessageDialog(null,"Appointment Date is mandotory.");
            }
        if(centre == 0){
                JOptionPane.showMessageDialog(null,"Vaccine Name is mandotory.");
            }
        if(vacName == 0){
                JOptionPane.showMessageDialog(null,"Vaccine Name is mandotory.");
            }
        if(phoneNumber.equals("")){
                JOptionPane.showMessageDialog(null,"Phone Number is mandotory.");
            }      
        else{
            JOptionPane.showMessageDialog(null,"Register Appointment Successfully!");
        }
        
        
        try{
            // open file, read and write the textfield string to the file
            FileWriter fw = new FileWriter("Appointment.txt",true);
            BufferedWriter bw = new BufferedWriter(fw);
            PrintWriter pw = new PrintWriter(bw);

            String vacString = null;
            String centreString = null;
            
            // check which which option do people choose 
            // read the index and change to string 
            if(vacName == 1){
                vacString = "AstraZeneca";
            }else if (vacName == 2){
                vacString = "Johnson&Johnson";
            }else if (vacName==3){
                vacString = "Pfizer";
            }
               
            // check which which option do people choose 
            // read the index and change to string 
            if(centre == 1){
                centreString = "Kuala Lumpur";
            }else if (centre == 2){
                centreString = "Selangor";
            }else if (centre==3){
                centreString = "Penang";
            }else if (centre == 4){
                centreString = "Sabah";
            }else if (centre==5){
                centreString = "Sarawak";
            }else if (centre == 6){
                centreString = "Negeri Sembilan";
            }else if (centre==7){
                centreString = "Malacca";
            }
            
            //  print string to the file
            pw.println(id+","+pname+","+date+","+centreString+","+vacString+","+phoneNumber);
            // confirm all the data has been written before close file
            pw.flush();
            //close file
            pw.close();
            
            // make all textfield are able to fill in again
            rvaid.setText(null);
            rvaname.setText(null);
            rvadate.setText(null);
            rvacentre.setSelectedIndex(0);
            rvavaccine.setSelectedIndex(0);
            rvaphoneNumber.setText(null);


        } catch (IOException ex) {

            rvaid.setText(null);
            rvaname.setText(null);
            rvadate.setText(null);
            rvacentre.setSelectedIndex(0);
            rvavaccine.setSelectedIndex(0);
            rvaphoneNumber.setText(null);

        }
    }//GEN-LAST:event_btn_rvaSubmitActionPerformed

    private void btn_rvpRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rvpRegisterActionPerformed
        
        // get input from people
        String id = rvpid.getText().toString();
        String pname = rvpname.getText().toString();
        String email = rvpemail.getText().toString();
        String phoneNumber = rvpphoneNumber.getText().toString();
        
        // if textfield is null show error message
        if(id.equals("")){
            JOptionPane.showMessageDialog(null,"ID is mandotory.");
        }
            if(pname.equals("")){
                JOptionPane.showMessageDialog(null,"Name is mandotory.");
            }    
            if(phoneNumber.equals("")){
                JOptionPane.showMessageDialog(null,"Phone Number is mandotory.");
            }
            if(email.equals("")){
                JOptionPane.showMessageDialog(null,"Email is mandotory.");
            }
        
        else{
            JOptionPane.showMessageDialog(null,"Register Program Successfully!");
        }

        try{
            // open file, read and write the textfield string to the file
            FileWriter fw = new FileWriter("Program.txt",true);
            BufferedWriter bw = new BufferedWriter(fw);
            PrintWriter pw = new PrintWriter(bw);
            
            //  print string to the file
            pw.println(id+","+pname+","+phoneNumber+","+email);
            // confirm all the data has been written before close file
            pw.flush();
            // close 
            pw.close();
            
            // make all textfield are able to fill in again
            rvpid.setText(null);
            rvpname.setText(null);
            rvpemail.setText(null);
            rvpphoneNumber.setText(null);


        } catch (IOException ex) {

            rvpid.setText(null);
            rvpname.setText(null);
            rvpemail.setText(null);
            rvpphoneNumber.setText(null);
        }
    }//GEN-LAST:event_btn_rvpRegisterActionPerformed

    private void rvpRegister1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rvpRegister1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rvpRegister1ActionPerformed

    private void btn_mvpConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mvpConfirmActionPerformed
        
        // get input from people
        String search_id = mvpID.getText();
        String newName = mvpName.getText();
        String newPhoneNumber = mvpPhoneNumber.getText();
        String newEmail = mvpEmail.getText();

        ArrayList<Program> programList = new ArrayList<>();

        if (!isFound) {
            JOptionPane.showMessageDialog(this, "Enter a valid ID to modify");
        } else if (search_id.isEmpty() || newName.isEmpty() || newPhoneNumber.isEmpty() || newEmail.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Fill all fields");
        } else {
            File file = new File("Program.txt");

            try {
                try (FileReader fr = new FileReader(file)) {
                    BufferedReader br = new BufferedReader(fr);
                    String data;
                    Program tempProgram;

                    while ((data = br.readLine()) != null) {
                        tempProgram = new Program(data);
                        if (tempProgram.getId().equals(search_id)) {
                            tempProgram.setName(newName);
                            tempProgram.setPhoneNumber(newPhoneNumber);
                            tempProgram.setEmail(newEmail);
                        }
                        programList.add(tempProgram);
                    }
                }

                try (PrintWriter pw = new PrintWriter(new FileWriter(file, false))) {
                    programList.forEach((program) -> {
                        pw.println(program.toString());
                    });
                    
                    JOptionPane.showMessageDialog(this, "Program Details updated");
                    btn_mvpConfirm.setEnabled(false);
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                }

            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        
        }
        
    }//GEN-LAST:event_btn_mvpConfirmActionPerformed

    private void btn_vvpViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vvpViewActionPerformed
        
        // set text field empty
        vvpName.setText("");
        vvpPhoneNumber.setText("");
        vvpEmail.setText("");
        isFound = false;
        
        // get input from people
        String search_id = vvpID.getText();
        
        // if search text field is null show error message
        if (search_id.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter an ID to view!");
        } else {
            
            File file = new File("Program.txt");

            try {
                
                // open file, read the file string to the textfield
                FileReader fr = new FileReader(file);
                BufferedReader br = new BufferedReader(fr);
                String data;
                Program program;

                // while the string is not null read the line
                while ((data = br.readLine()) != null) {
                    program = new Program(data);
                    // if the string have the id same with the search id print the string 
                    if (program.getId().equals(search_id)) {
                        isFound = true;
                        vvpName.setText(program.getName());
                        vvpPhoneNumber.setText(program.getPhoneNumber());
                        vvpEmail.setText(program.getEmail());
                        return;
                    }
                }
                // if txt file cannot find the id show error message
                JOptionPane.showMessageDialog(this, "ID is not Available! Please enter again!");
                vvpID.setText(null);
                
            } catch (FileNotFoundException ex) {

            } catch (IOException ex) {

            }
        }        
    }//GEN-LAST:event_btn_vvpViewActionPerformed

    private void btn_vvaViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vvaViewActionPerformed
        
        // set text field empty
        vvaName.setText("");
        vvaDate.setText("");
        vvaCentre.setText("");
        vvaVaccine.setText("");
        vvaPhoneNumber.setText("");
        isFound = false;
        
        // get input from people
        String search_id = vvaID.getText();
        
        // if search text field is null show error message
        if (search_id.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter an ID to view!");
        } else {
            File file = new File("Appointment.txt");

            try {
                
                // open file, read the file string to the textfield
                FileReader fr = new FileReader(file);
                BufferedReader br = new BufferedReader(fr);
                String data;
                Appointment app;
                
                // while the string is not null read the line
                while ((data = br.readLine()) != null) {
                    app = new Appointment(data);
                    // if the string have the id same with the search id print the string 
                    if (app.getID().equals(search_id)) {
                        isFound = true;
                        vvaName.setText(app.getName());
                        vvaDate.setText(app.getDate());
                        vvaCentre.setText(app.getCentre());
                        vvaVaccine.setText(app.getVaccine());
                        vvaPhoneNumber.setText(app.getPhoneNumber());
                        return;
                    }
                }
                // if txt file cannot find the id show error message
                JOptionPane.showMessageDialog(this, "ID is not Available! Please enter again!");
                vvaID.setText(null); 
                
            } catch (FileNotFoundException ex) {

            } catch (IOException ex) {

            }
        } 
    }//GEN-LAST:event_btn_vvaViewActionPerformed

    private void btn_vvsConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vvsConfirmActionPerformed
        
        // set text field empty
        vvsName.setText("");
        vvsCitizen.setText("");
        vvsDate.setText("");
        vvsStatus.setText("");
        isFound = false;
        
        // get input from people
        String search_id = vvsID.getText();
        
        // if search text field is null show error message
        if (search_id.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter an ID!");
        } else {
            File file = new File("Status.txt");

            try {
                
                // open file, read the file string to the textfield
                FileReader fr = new FileReader(file);
                BufferedReader br = new BufferedReader(fr);
                String data;
                Status status;
                
                // while the string is not null read the line
                while ((data = br.readLine()) != null) {
                    status = new Status(data);
                    if (status.getId().equals(search_id)) {
                        isFound = true;
                        vvsName.setText(status.getName());
                        vvsCitizen.setText(status.getCitizen());
                        vvsDate.setText(status.getDate());
                        vvsStatus.setText(status.getStatus());
                        return;
                    }
                }
                // if txt file cannot find the id show error message
                JOptionPane.showMessageDialog(this, "ID is not Available! Please enter again!");
                vvsID.setText(null);
                
            } catch (FileNotFoundException ex) {

            } catch (IOException ex) {

            }
        } 
    }//GEN-LAST:event_btn_vvsConfirmActionPerformed

    private void btn_cvaConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cvaConfirmActionPerformed
        
        // get input from people
        String delete_id = cvaID.getText();
        
        ArrayList<Appointment> appointmentList = new ArrayList<>();
        
        
         if (delete_id.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter an ID to cancel!");
         } else {
            File file = new File("Appointment.txt");

            try {
                try (FileReader fr = new FileReader(file)) {
                    BufferedReader br = new BufferedReader(fr);
                    String data;
                    Appointment tempApp;

                    while ((data = br.readLine()) != null) {
                        tempApp = new Appointment(data);
                        if (!tempApp.getID().equals(delete_id)) {
                            appointmentList.add(tempApp);
                        }                        
                    }
                }

                try (PrintWriter pw = new PrintWriter(new FileWriter(file, false))) {
                    appointmentList.forEach((appointment) -> {
                        pw.println(appointment.toString());
                    });
                    JOptionPane.showMessageDialog(this, "Appointment canceled");
                    cvaID.setText(null);

                } catch (IOException ex) {

                }

            } catch (FileNotFoundException ex) {

            } catch (IOException ex) {
            
            }
        }
    }//GEN-LAST:event_btn_cvaConfirmActionPerformed

    private void jLabelLogoutMenuBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLogoutMenuBarMouseClicked
        int response = JOptionPane.showConfirmDialog(null, "Please Confitm to LOGOUT!", "Select Option", JOptionPane.YES_NO_OPTION);
        if (response == JOptionPane.YES_OPTION){
            People people = new People();
            people.logout();
            dispose();
        }
    }//GEN-LAST:event_jLabelLogoutMenuBarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(People_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(People_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(People_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(People_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new People_menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cvaConfirm;
    private javax.swing.JButton btn_mvpConfirm;
    private javax.swing.JButton btn_rvaSubmit;
    private javax.swing.JButton btn_rvpRegister;
    private javax.swing.JButton btn_vvaView;
    private javax.swing.JButton btn_vvpView;
    private javax.swing.JButton btn_vvsConfirm;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cvaID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelLogoutMenuBar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField mvpEmail;
    private javax.swing.JTextField mvpID;
    private javax.swing.JTextField mvpName;
    private javax.swing.JTextField mvpPhoneNumber;
    private javax.swing.JComboBox<String> rvacentre;
    private javax.swing.JTextField rvadate;
    private javax.swing.JTextField rvaid;
    private javax.swing.JTextField rvaname;
    private javax.swing.JTextField rvaphoneNumber;
    private javax.swing.JComboBox<String> rvavaccine;
    private javax.swing.JButton rvpRegister1;
    private javax.swing.JTextField rvpemail;
    private javax.swing.JTextField rvpid;
    private javax.swing.JTextField rvpname;
    private javax.swing.JTextField rvpphoneNumber;
    private javax.swing.JTextField vvaCentre;
    private javax.swing.JTextField vvaDate;
    private javax.swing.JTextField vvaID;
    private javax.swing.JTextField vvaName;
    private javax.swing.JTextField vvaPhoneNumber;
    private javax.swing.JTextField vvaVaccine;
    private javax.swing.JTextField vvpEmail;
    private javax.swing.JTextField vvpID;
    private javax.swing.JTextField vvpName;
    private javax.swing.JTextField vvpPhoneNumber;
    private javax.swing.JTextField vvsCitizen;
    private javax.swing.JTextField vvsDate;
    private javax.swing.JTextField vvsID;
    private javax.swing.JTextField vvsName;
    private javax.swing.JTextField vvsStatus;
    // End of variables declaration//GEN-END:variables
}
