/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import Classes.Committee;
import javax.swing.JOptionPane;

/**
 *
 * @author JUN WEI
 */
public class Personnel_Menu extends javax.swing.JFrame {

    /**
     * Creates new form Personnel_Menu
     */
    public Personnel_Menu() {
        initComponents();
    }
    Committee committee = new Committee();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelUpdateVaccineMenuBar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelUpdatePeoplehomebar = new javax.swing.JLabel();
        jLabelLogoutMenuBar = new javax.swing.JLabel();
        jLabelUpdateAppointmentMenuBar = new javax.swing.JLabel();
        jLabelUpdateCommitteeMenuBar = new javax.swing.JLabel();
        jLabelAppointment = new javax.swing.JLabel();
        jLabelCommittee = new javax.swing.JLabel();
        jLabelPeople = new javax.swing.JLabel();
        jLabelVaccine = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabelUpdateVaccineMenuBar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelUpdateVaccineMenuBar.setText("Update Vaccine");
        jLabelUpdateVaccineMenuBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelUpdateVaccineMenuBarMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Home");

        jLabelUpdatePeoplehomebar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelUpdatePeoplehomebar.setText("Update People");
        jLabelUpdatePeoplehomebar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelUpdatePeoplehomebarMouseClicked(evt);
            }
        });

        jLabelLogoutMenuBar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelLogoutMenuBar.setText("Logout");
        jLabelLogoutMenuBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLogoutMenuBarMouseClicked(evt);
            }
        });

        jLabelUpdateAppointmentMenuBar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelUpdateAppointmentMenuBar.setText("Update Appointment");
        jLabelUpdateAppointmentMenuBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelUpdateAppointmentMenuBarMouseClicked(evt);
            }
        });

        jLabelUpdateCommitteeMenuBar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelUpdateCommitteeMenuBar.setText("Update Committee");
        jLabelUpdateCommitteeMenuBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelUpdateCommitteeMenuBarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addGap(75, 75, 75)
                .addComponent(jLabelUpdatePeoplehomebar)
                .addGap(71, 71, 71)
                .addComponent(jLabelUpdateVaccineMenuBar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(jLabelUpdateAppointmentMenuBar)
                .addGap(70, 70, 70)
                .addComponent(jLabelUpdateCommitteeMenuBar)
                .addGap(56, 56, 56)
                .addComponent(jLabelLogoutMenuBar)
                .addGap(39, 39, 39))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelUpdatePeoplehomebar)
                    .addComponent(jLabelUpdateVaccineMenuBar)
                    .addComponent(jLabelUpdateAppointmentMenuBar)
                    .addComponent(jLabelLogoutMenuBar)
                    .addComponent(jLabelUpdateCommitteeMenuBar))
                .addGap(55, 55, 55))
        );

        jLabelAppointment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/appointment.png"))); // NOI18N
        jLabelAppointment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAppointmentMouseClicked(evt);
            }
        });

        jLabelCommittee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/audience.png"))); // NOI18N
        jLabelCommittee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCommitteeMouseClicked(evt);
            }
        });

        jLabelPeople.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/user.png"))); // NOI18N
        jLabelPeople.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPeopleMouseClicked(evt);
            }
        });

        jLabelVaccine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/vaccine.png"))); // NOI18N
        jLabelVaccine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelVaccineMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel6.setText("Update Committee");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel7.setText("Update People");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel8.setText("Update Vaccine");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel9.setText("Update Appointment");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("Welcome Committee!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel7)
                        .addGap(171, 171, 171)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabelPeople)
                        .addGap(123, 123, 123)
                        .addComponent(jLabelVaccine)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelAppointment)
                        .addGap(119, 119, 119))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(130, 130, 130)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCommittee)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(8, 8, 8)))
                .addGap(61, 61, 61))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCommittee)
                            .addComponent(jLabelAppointment))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(180, 180, 180)
                                .addComponent(jLabelVaccine)
                                .addGap(31, 31, 31))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelPeople)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addContainerGap(148, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelUpdateVaccineMenuBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelUpdateVaccineMenuBarMouseClicked
        UpdateVaccine updatevac = new UpdateVaccine();
        updatevac.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabelUpdateVaccineMenuBarMouseClicked

    private void jLabelUpdatePeoplehomebarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelUpdatePeoplehomebarMouseClicked
        // TODO add your handling code here:
        Update_People updatep = new Update_People();
        updatep.setVisible(true);
        dispose();

    }//GEN-LAST:event_jLabelUpdatePeoplehomebarMouseClicked

    private void jLabelLogoutMenuBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLogoutMenuBarMouseClicked
        int response = JOptionPane.showConfirmDialog(null, "Please Confitm to LOGOUT!", "Select Option", JOptionPane.YES_NO_OPTION);
        if (response == JOptionPane.YES_OPTION){
            committee.logout();
            dispose();
        }
    }//GEN-LAST:event_jLabelLogoutMenuBarMouseClicked

    private void jLabelUpdateAppointmentMenuBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelUpdateAppointmentMenuBarMouseClicked
        UpdateAppointment updateapt = new UpdateAppointment();
        updateapt.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabelUpdateAppointmentMenuBarMouseClicked

    private void jLabelUpdateCommitteeMenuBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelUpdateCommitteeMenuBarMouseClicked
        // TODO add your handling code here:
        Update_Committee updatecommit = new Update_Committee();
        updatecommit.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabelUpdateCommitteeMenuBarMouseClicked

    private void jLabelPeopleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPeopleMouseClicked
        Update_People updatep = new Update_People();
        updatep.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabelPeopleMouseClicked

    private void jLabelVaccineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelVaccineMouseClicked
        // TODO add your handling code here:
        UpdateVaccine updatevac = new UpdateVaccine();
        updatevac.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabelVaccineMouseClicked

    private void jLabelAppointmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAppointmentMouseClicked
        // TODO add your handling code here:
        UpdateAppointment updateapt = new UpdateAppointment();
        updateapt.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabelAppointmentMouseClicked

    private void jLabelCommitteeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCommitteeMouseClicked
        // TODO add your handling code here:
        Update_Committee updatecommit = new Update_Committee();
        updatecommit.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabelCommitteeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Personnel_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Personnel_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Personnel_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Personnel_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Personnel_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAppointment;
    private javax.swing.JLabel jLabelCommittee;
    private javax.swing.JLabel jLabelLogoutMenuBar;
    private javax.swing.JLabel jLabelPeople;
    private javax.swing.JLabel jLabelUpdateAppointmentMenuBar;
    private javax.swing.JLabel jLabelUpdateCommitteeMenuBar;
    private javax.swing.JLabel jLabelUpdatePeoplehomebar;
    private javax.swing.JLabel jLabelUpdateVaccineMenuBar;
    private javax.swing.JLabel jLabelVaccine;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
