/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import Classes.*;


import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.Writer;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author JUN WEI
 */
public class UpdateAppointment extends javax.swing.JFrame {

    /**
     * Creates new form UpdateAppointment
     */
    
    public UpdateAppointment() {
        initComponents();
        ViewAppointment();
    }
    
    Committee committee = new Committee();
    Appointment appointment = new Appointment();
    Vaccine vaccine = new Vaccine();
    Centre centre = new Centre();
    People people = new People();
    
    public void ViewAppointment(){
       String appointment[]; 
       List<String> appointmentlist = new ArrayList<>(); 
       String line = ""; 
       DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
       tblModel.setRowCount(0);//Reset jTable, Clear all data
       
        appointmentlist = committee.ViewAppointment();
        for (String element : appointmentlist) {
            appointment = element.split(",");
               
            tblModel.addRow(appointment);

            }
    }
    /**
;     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelUpdateVaccineMenuBar = new javax.swing.JLabel();
        jLabelHomeMenuBar = new javax.swing.JLabel();
        jLabelUpdatePeopleMenuBar = new javax.swing.JLabel();
        jLabelLogoutMenuBar = new javax.swing.JLabel();
        jLabelUpdateCommitteeMenuBar = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldAppID = new javax.swing.JTextField();
        jTextFieldAppName = new javax.swing.JTextField();
        jTextFieldAppDate = new javax.swing.JTextField();
        jTextFieldAppPN = new javax.swing.JTextField();
        jButtonClearApp = new javax.swing.JButton();
        jButtonAddApp = new javax.swing.JButton();
        jButtonEditApp = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jButtonDeleteApp = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxVacCentre = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldSearchApp = new javax.swing.JTextField();
        jComboBoxVaccine = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldAppIC = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        jLabelUpdateVaccineMenuBar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelUpdateVaccineMenuBar.setText("Update Vaccine");
        jLabelUpdateVaccineMenuBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelUpdateVaccineMenuBarMouseClicked(evt);
            }
        });

        jLabelHomeMenuBar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelHomeMenuBar.setText("Home");
        jLabelHomeMenuBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHomeMenuBarMouseClicked(evt);
            }
        });

        jLabelUpdatePeopleMenuBar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelUpdatePeopleMenuBar.setText("Update People");
        jLabelUpdatePeopleMenuBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelUpdatePeopleMenuBarMouseClicked(evt);
            }
        });

        jLabelLogoutMenuBar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelLogoutMenuBar.setText("Logout");
        jLabelLogoutMenuBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLogoutMenuBarMouseClicked(evt);
            }
        });

        jLabelUpdateCommitteeMenuBar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelUpdateCommitteeMenuBar.setText("Update Committee");
        jLabelUpdateCommitteeMenuBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelUpdateCommitteeMenuBarMouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setText("Update Appointment");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabelHomeMenuBar)
                .addGap(110, 110, 110)
                .addComponent(jLabelUpdatePeopleMenuBar)
                .addGap(121, 121, 121)
                .addComponent(jLabelUpdateVaccineMenuBar)
                .addGap(108, 108, 108)
                .addComponent(jLabel13)
                .addGap(116, 116, 116)
                .addComponent(jLabelUpdateCommitteeMenuBar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelLogoutMenuBar)
                .addGap(49, 49, 49))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHomeMenuBar)
                    .addComponent(jLabelUpdatePeopleMenuBar)
                    .addComponent(jLabelUpdateVaccineMenuBar)
                    .addComponent(jLabelUpdateCommitteeMenuBar)
                    .addComponent(jLabelLogoutMenuBar)
                    .addComponent(jLabel13))
                .addGap(55, 55, 55))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel6.setText("Name:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel7.setText("ID:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel10.setText("Date(dd/mm/yy)");

        jTextFieldAppID.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextFieldAppID.setToolTipText("");

        jTextFieldAppName.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextFieldAppName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAppNameActionPerformed(evt);
            }
        });

        jTextFieldAppDate.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jTextFieldAppPN.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jButtonClearApp.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonClearApp.setText("Clear");
        jButtonClearApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearAppActionPerformed(evt);
            }
        });

        jButtonAddApp.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonAddApp.setText("Add");
        jButtonAddApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddAppActionPerformed(evt);
            }
        });

        jButtonEditApp.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonEditApp.setText("Edit");
        jButtonEditApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditAppActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "IC/Passport", "Name", "Date", "Centre", "Vaccine", "Phone Number "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable1.setRowHeight(25);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(5).setMinWidth(7);
        }

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel11.setText("Updating Appointment");

        jButtonDeleteApp.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonDeleteApp.setText("Delete");
        jButtonDeleteApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteAppActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel8.setText("Centre");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel9.setText("Phone Number:");

        jComboBoxVacCentre.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jComboBoxVacCentre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Centre", "Kuala Lumpur", "Selangor", "Penang", "Sabah", "Sarawak", "Negeri Sembilan", "Malacca" }));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel12.setText("IC/Passport:");

        jTextFieldSearchApp.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextFieldSearchApp.setText("Search ID");
        jTextFieldSearchApp.setToolTipText("Enter an ID to search");
        jTextFieldSearchApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSearchAppActionPerformed(evt);
            }
        });

        jComboBoxVaccine.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jComboBoxVaccine.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Vaccine", "AstraZeneca", "Johnson&Johnson", "Pfizer" }));
        jComboBoxVaccine.setMinimumSize(new java.awt.Dimension(197, 33));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel14.setText("Vaccine:");

        jTextFieldAppIC.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonAddApp, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonClearApp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEditApp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDeleteApp))
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextFieldAppPN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                        .addComponent(jTextFieldAppIC, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextFieldAppDate, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldAppName, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextFieldAppID, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxVaccine, javax.swing.GroupLayout.Alignment.LEADING, 0, 399, Short.MAX_VALUE)
                        .addComponent(jComboBoxVacCentre, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1092, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSearchApp, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSearchApp, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldAppID, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addGap(1, 1, 1)
                        .addComponent(jTextFieldAppName, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxVaccine, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldAppIC, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldAppPN, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxVacCentre, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldAppDate, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAddApp)
                            .addComponent(jButtonClearApp)
                            .addComponent(jButtonEditApp)
                            .addComponent(jButtonDeleteApp))
                        .addGap(8, 8, 8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelUpdateVaccineMenuBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelUpdateVaccineMenuBarMouseClicked
        UpdateVaccine updatevac = new UpdateVaccine();
        updatevac.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabelUpdateVaccineMenuBarMouseClicked

    private void jLabelHomeMenuBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHomeMenuBarMouseClicked
        Personnel_Menu pm = new Personnel_Menu();
        pm.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabelHomeMenuBarMouseClicked

    private void jLabelUpdatePeopleMenuBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelUpdatePeopleMenuBarMouseClicked
        Update_People updatep = new Update_People();
        updatep.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabelUpdatePeopleMenuBarMouseClicked

    private void jLabelLogoutMenuBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLogoutMenuBarMouseClicked
        int response = JOptionPane.showConfirmDialog(null, "Please Confitm to LOGOUT!", "Select Option", JOptionPane.YES_NO_OPTION);
        if (response == JOptionPane.YES_OPTION){
            committee.logout();
            dispose();
        }
    }//GEN-LAST:event_jLabelLogoutMenuBarMouseClicked

    private void jLabelUpdateCommitteeMenuBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelUpdateCommitteeMenuBarMouseClicked
        Update_Committee updatecommit = new Update_Committee();
        updatecommit.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabelUpdateCommitteeMenuBarMouseClicked

    private void jTextFieldAppNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAppNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAppNameActionPerformed

    private void jButtonClearAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearAppActionPerformed
        int response = JOptionPane.showConfirmDialog(null, "Please Confitm to CLEAR!", "Select Option", JOptionPane.YES_NO_OPTION);
        if (response == JOptionPane.YES_OPTION){
            String clear = "";
            jTextFieldAppDate.setText(clear);
            jTextFieldAppID.setText(clear);
            jTextFieldAppName.setText(clear);
            jTextFieldAppPN.setText(clear);
            jTextFieldAppIC.setText(clear);
            jComboBoxVaccine.setSelectedItem("Select Vaccine");
            jComboBoxVacCentre.setSelectedItem("Select Centre");
        }
    }//GEN-LAST:event_jButtonClearAppActionPerformed

    private void jButtonAddAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddAppActionPerformed
        int response = JOptionPane.showConfirmDialog(null, "Please Confitm to ADD!", "Select Option", JOptionPane.YES_NO_OPTION);
        if (response == JOptionPane.YES_OPTION){
            String date,ID,appName,phoneNumber,appVaccine,Centre,appIC;
            Object appCentre,AppVaccine;

            ID = jTextFieldAppID.getText();
            appName = jTextFieldAppName.getText();
            date = jTextFieldAppDate.getText();
            appCentre = jComboBoxVacCentre.getSelectedItem();
            appIC = jTextFieldAppIC.getText();
            AppVaccine = jComboBoxVaccine.getSelectedItem();
            phoneNumber = jTextFieldAppPN.getText();

            appVaccine = AppVaccine.toString();
            Centre = appCentre.toString();
            if(ID.length()==0 || appName.length()==0 || date.length()==0 || Centre=="Select Center" || appVaccine.length()==0 || phoneNumber.length()==0 || appIC.length()==0){
                JOptionPane.showMessageDialog(null,"Form Incomplete!");
            }else if(committee.checkDuplicateAppointmentIC(appIC) == true){
                JOptionPane.showMessageDialog(null,"Appointment already exist!");
            }
            else if(committee.checkDuplicateAppointmentID(ID)){
                JOptionPane.showMessageDialog(null,"Appointment ID already exist!");
            }
            else if(committee.checkPeopleExist(appName,appIC)!=true){
                JOptionPane.showMessageDialog(null,"People is not in record! Please register first!");
            }
            else{
                appointment.setID(ID);
                people.setName(appName);
                people.setIC(appIC);
                appointment.setDate(date);
                centre.setCentre(Centre);
                vaccine.setVacName(appVaccine);
                people.setPhoneNumber(phoneNumber);

                if(committee.checkVaccineAvailability(appVaccine, Centre)!=true){
                    JOptionPane.showMessageDialog(null,appVaccine+" ran out! Please restock!");
                }
                else{
                    JOptionPane.showMessageDialog(null,committee.addAppointment(appointment.getID(), people.getIC(), people.getName(), appointment.getDate(), centre.getCentre(), vaccine.getVacName(), people.getPhoneNumber()));
                    String clear = "";
                    jTextFieldAppDate.setText(clear);
                    jTextFieldAppID.setText(clear);
                    jTextFieldAppName.setText(clear);
                    jTextFieldAppPN.setText(clear);
                    jTextFieldAppIC.setText(clear);
                    jComboBoxVaccine.setSelectedItem("Select Vaccine");
                    jComboBoxVacCentre.setSelectedItem("Select Centre");
                }
            }

            ViewAppointment();
        }
    }//GEN-LAST:event_jButtonAddAppActionPerformed

    private void jButtonEditAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditAppActionPerformed
        int response = JOptionPane.showConfirmDialog(null, "Please Confitm to EDIT!", "Select Option", JOptionPane.YES_NO_OPTION);
        if (response == JOptionPane.YES_OPTION){
            String date,ID,name,phoneNumber,appVaccine,Centre,IC;
            String clear = "";
            Object appCentre,AppVaccine;

            ID = jTextFieldAppID.getText();
            IC = jTextFieldAppIC.getText();
            name = jTextFieldAppName.getText();
            date = jTextFieldAppDate.getText();
            appCentre = jComboBoxVacCentre.getSelectedItem();
            AppVaccine = jComboBoxVaccine.getSelectedItem();
            phoneNumber = jTextFieldAppPN.getText();

            appVaccine = AppVaccine.toString();
            Centre = appCentre.toString();
            if(ID.length()==0 || name.length()==0 || date.length()==0 || Centre=="Select Center" || appVaccine.length()==0 || phoneNumber.length()==0 || IC.length()==0){
                JOptionPane.showMessageDialog(null,"Form Incomplete!");
            }
            else if(committee.checkPeopleExist(name,IC)!=true){
                JOptionPane.showMessageDialog(null,"People is not in record! Please register first!");
            }
            else{
                appointment.setID(ID);
                people.setIC(IC);
                people.setName(name);
                appointment.setDate(date);
                centre.setCentre(Centre);
                vaccine.setVacName(appVaccine);
                people.setPhoneNumber(phoneNumber);

                if(committee.checkVaccineAvailability(appVaccine, Centre)!=true){
                    JOptionPane.showMessageDialog(null,appVaccine+" ran out! Please restock!");
                }
                else{
                    JOptionPane.showMessageDialog(null,committee.edit(appointment.getID(),people.getIC(),people.getName(),appointment.getDate(),centre.getCentre(),vaccine.getVacName(), people.getPhoneNumber()));

                    jTextFieldAppDate.setText(clear);
                    jTextFieldAppIC.setText(clear);
                    jTextFieldAppID.setText(clear);
                    jTextFieldAppName.setText(clear);
                    jTextFieldAppPN.setText(clear);
                    jComboBoxVaccine.setSelectedItem("Select Vaccine");
                    jTextFieldSearchApp.setText(clear);
                    jComboBoxVacCentre.setSelectedItem("Select Centre");
                }
            }
            ViewAppointment();
        }
    }//GEN-LAST:event_jButtonEditAppActionPerformed

    private void jButtonDeleteAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteAppActionPerformed
        int response = JOptionPane.showConfirmDialog(null, "Please Confitm to DELETE!", "Select Option", JOptionPane.YES_NO_OPTION);
        if (response == JOptionPane.YES_OPTION){
            ArrayList<String> appointmentlist = new ArrayList<String>();
            appointmentlist.clear();
            String ID;
            ID = (jTextFieldAppID.getText()).trim();

            appointment.setID(ID);

            if(ID.isEmpty()){
                JOptionPane.showMessageDialog(null,"Enter an ID to delete!");
            }
            else{
                JOptionPane.showMessageDialog(null,committee.deleteAppointment(appointment.getID()));
            ViewAppointment();    
        }
        }
    }//GEN-LAST:event_jButtonDeleteAppActionPerformed

    private void jTextFieldSearchAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSearchAppActionPerformed
        boolean found = false;
        List<String> searchlist = new ArrayList<>();
        String searchID[];
        String line,ID;
        ID = (jTextFieldSearchApp.getText()).trim();
        appointment.setID(ID);

        if(ID.isEmpty()){
            JOptionPane.showMessageDialog(null,"Enter an ID to delete!");
            ViewAppointment();
        }
        else{
            searchlist = committee.searchAppointment(appointment.getID());
            for (String element : searchlist) {
                searchID = element.split(",");

                DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
                tblModel.setRowCount(0);
                tblModel.addRow(searchID);

            }
        }
    }//GEN-LAST:event_jTextFieldSearchAppActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateAppointment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateAppointment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddApp;
    private javax.swing.JButton jButtonClearApp;
    private javax.swing.JButton jButtonDeleteApp;
    private javax.swing.JButton jButtonEditApp;
    private javax.swing.JComboBox<String> jComboBoxVacCentre;
    private javax.swing.JComboBox<String> jComboBoxVaccine;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelHomeMenuBar;
    private javax.swing.JLabel jLabelLogoutMenuBar;
    private javax.swing.JLabel jLabelUpdateCommitteeMenuBar;
    private javax.swing.JLabel jLabelUpdatePeopleMenuBar;
    private javax.swing.JLabel jLabelUpdateVaccineMenuBar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldAppDate;
    private javax.swing.JTextField jTextFieldAppIC;
    private javax.swing.JTextField jTextFieldAppID;
    private javax.swing.JTextField jTextFieldAppName;
    private javax.swing.JTextField jTextFieldAppPN;
    private javax.swing.JTextField jTextFieldSearchApp;
    // End of variables declaration//GEN-END:variables
}
