/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JUN WEI
 */
package GUI;
import Classes.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

public class Update_Committee extends javax.swing.JFrame {

    /**
     * Creates new form Update_Committee
     */
    public Update_Committee() {
        initComponents();
        ViewCommittee();
    }
    Committee committee = new Committee();
    
    public void ViewCommittee(){
       String committeel[]; 
       List<String> committeelist = new ArrayList<>(); 
       String line = ""; 
       DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
       tblModel.setRowCount(0);//Reset jTable, Clear all data
       
        committeelist = committee.ViewCommittee();
        for (String element : committeelist) {
            committeel = element.split(",");
               
            tblModel.addRow(committeel);

            }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelUpdateVaccineMenuBar = new javax.swing.JLabel();
        jLabelHomeMenuBar = new javax.swing.JLabel();
        jLabelUpdatePeopleMenuBar = new javax.swing.JLabel();
        jLabelLogoutMenuBar = new javax.swing.JLabel();
        jLabelUpdateCommitteeMenuBar = new javax.swing.JLabel();
        jLabelUpdateAppointmentMenuBar = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jTextFieldName = new javax.swing.JTextField();
        jTextFieldaddPassword = new javax.swing.JTextField();
        jButtonClear = new javax.swing.JButton();
        jButtonaddCommittee = new javax.swing.JButton();
        jButtonEditCommittee = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jButtonDeleteCommittee = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldIC = new javax.swing.JTextField();
        jTextFieldSearchInput = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldDOB = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        jLabelUpdateVaccineMenuBar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelUpdateVaccineMenuBar.setText("Update Vaccine");
        jLabelUpdateVaccineMenuBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelUpdateVaccineMenuBarMouseClicked(evt);
            }
        });

        jLabelHomeMenuBar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelHomeMenuBar.setText("Home");
        jLabelHomeMenuBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHomeMenuBarMouseClicked(evt);
            }
        });

        jLabelUpdatePeopleMenuBar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelUpdatePeopleMenuBar.setText("Update People");
        jLabelUpdatePeopleMenuBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelUpdatePeopleMenuBarMouseClicked(evt);
            }
        });

        jLabelLogoutMenuBar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelLogoutMenuBar.setText("Logout");
        jLabelLogoutMenuBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLogoutMenuBarMouseClicked(evt);
            }
        });

        jLabelUpdateCommitteeMenuBar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelUpdateCommitteeMenuBar.setText("Update Committee");
        jLabelUpdateCommitteeMenuBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelUpdateCommitteeMenuBarMouseClicked(evt);
            }
        });

        jLabelUpdateAppointmentMenuBar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelUpdateAppointmentMenuBar.setText("Update Appointment");
        jLabelUpdateAppointmentMenuBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelUpdateAppointmentMenuBarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabelHomeMenuBar)
                .addGap(89, 89, 89)
                .addComponent(jLabelUpdatePeopleMenuBar)
                .addGap(93, 93, 93)
                .addComponent(jLabelUpdateVaccineMenuBar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelUpdateAppointmentMenuBar)
                .addGap(67, 67, 67)
                .addComponent(jLabelUpdateCommitteeMenuBar)
                .addGap(58, 58, 58)
                .addComponent(jLabelLogoutMenuBar)
                .addGap(47, 47, 47))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUpdatePeopleMenuBar)
                    .addComponent(jLabelHomeMenuBar)
                    .addComponent(jLabelUpdateVaccineMenuBar)
                    .addComponent(jLabelUpdateCommitteeMenuBar)
                    .addComponent(jLabelUpdateAppointmentMenuBar)
                    .addComponent(jLabelLogoutMenuBar))
                .addGap(63, 63, 63))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel6.setText("Name:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel7.setText("ID:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel10.setText("Password:");

        jTextFieldID.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextFieldID.setToolTipText("");

        jTextFieldName.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jTextFieldaddPassword.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jButtonClear.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jButtonaddCommittee.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonaddCommittee.setText("Add");
        jButtonaddCommittee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonaddCommitteeActionPerformed(evt);
            }
        });

        jButtonEditCommittee.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonEditCommittee.setText("Edit");
        jButtonEditCommittee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditCommitteeActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NRIC/Passport", "Name", "DOB"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable1.setRowHeight(25);
        jScrollPane1.setViewportView(jTable1);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel11.setText("Updating Committee");

        jButtonDeleteCommittee.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonDeleteCommittee.setText("Delete");
        jButtonDeleteCommittee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteCommitteeActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel12.setText("D.O.B (dd/mm/yy):");

        jTextFieldIC.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jTextFieldSearchInput.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextFieldSearchInput.setText("Search ID");
        jTextFieldSearchInput.setToolTipText("Enter an ID to search");
        jTextFieldSearchInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSearchInputActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel14.setText("NRIC/Passport:");

        jTextFieldDOB.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextFieldDOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDOBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldIC)
                    .addComponent(jTextFieldID)
                    .addComponent(jTextFieldaddPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldName)
                    .addComponent(jTextFieldDOB)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonaddCommittee)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonClear)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonEditCommittee)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonDeleteCommittee))
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldSearchInput, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 958, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSearchInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addGap(1, 1, 1)
                        .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldIC, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldaddPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonaddCommittee)
                            .addComponent(jButtonClear)
                            .addComponent(jButtonEditCommittee)
                            .addComponent(jButtonDeleteCommittee)))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelUpdateVaccineMenuBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelUpdateVaccineMenuBarMouseClicked
        UpdateVaccine updatevac = new UpdateVaccine();
        updatevac.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabelUpdateVaccineMenuBarMouseClicked

    private void jLabelHomeMenuBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHomeMenuBarMouseClicked
        Personnel_Menu pm = new Personnel_Menu();
        pm.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabelHomeMenuBarMouseClicked

    private void jLabelUpdatePeopleMenuBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelUpdatePeopleMenuBarMouseClicked
        // TODO add your handling code here:
        Update_People updatep = new Update_People();
        updatep.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabelUpdatePeopleMenuBarMouseClicked

    private void jLabelLogoutMenuBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLogoutMenuBarMouseClicked
        int response = JOptionPane.showConfirmDialog(null, "Please Confitm to LOGOUT!", "Select Option", JOptionPane.YES_NO_OPTION);
        if (response == JOptionPane.YES_OPTION){
            committee.logout();
            dispose();
        }
    }//GEN-LAST:event_jLabelLogoutMenuBarMouseClicked

    private void jLabelUpdateCommitteeMenuBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelUpdateCommitteeMenuBarMouseClicked
        UpdateAppointment updateapt = new UpdateAppointment();
        updateapt.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabelUpdateCommitteeMenuBarMouseClicked

    private void jLabelUpdateAppointmentMenuBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelUpdateAppointmentMenuBarMouseClicked
        // TODO add your handling code here:
        UpdateAppointment updateapt = new UpdateAppointment();
        updateapt.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabelUpdateAppointmentMenuBarMouseClicked

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        int response = JOptionPane.showConfirmDialog(null, "Please Confitm to Clear!", "Select Option", JOptionPane.YES_NO_OPTION);
        if (response == JOptionPane.YES_OPTION){
            String clear = "";
            jTextFieldID.setText(clear);
            jTextFieldName.setText(clear);
            jTextFieldIC.setText(clear);
            jTextFieldDOB.setText(clear);
            jTextFieldaddPassword.setText(clear);
        }
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonaddCommitteeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonaddCommitteeActionPerformed
        int response = JOptionPane.showConfirmDialog(null, "Please Confitm to Add!", "Select Option", JOptionPane.YES_NO_OPTION);
        if (response == JOptionPane.YES_OPTION){
            People people = new People();
            Committee committee = new Committee();
            String ID,name,IC,DOB,password,clear;

            clear = "";
            ID = (jTextFieldID.getText()).trim();
            name = (jTextFieldName.getText()).trim();
            IC = (jTextFieldIC.getText()).trim();
            DOB = (jTextFieldDOB.getText().trim());

            password = (jTextFieldaddPassword.getText().trim());

            if(ID.length()==0 || name.length()==0 || IC.length()==0 || DOB.length()==0 || password.length()==0){
                JOptionPane.showMessageDialog(null,"Form Incomplete!");
            }else if(committee.checkDuplicateCommittee(ID, IC)==true){
                JOptionPane.showMessageDialog(null,"ID or Name already exist! Please try again!");
            }else{
                committee.setName(name);
                committee.setDOB(DOB);
                committee.setPassword(password);
                name = committee.getName();
                DOB = committee.getDOB();
                password = committee.getPassword();
                JOptionPane.showMessageDialog(null,committee.addCommittee(ID,IC,name,DOB,password));

            }
            ViewCommittee();
            jTextFieldID.setText(clear);
            jTextFieldName.setText(clear);
            jTextFieldIC.setText(clear);
            jTextFieldDOB.setText(clear);
            jTextFieldaddPassword.setText(clear);
        }
    }//GEN-LAST:event_jButtonaddCommitteeActionPerformed

    private void jButtonEditCommitteeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditCommitteeActionPerformed
        int response = JOptionPane.showConfirmDialog(null, "Please Confitm to EDIT!", "Select Option", JOptionPane.YES_NO_OPTION);
        if (response == JOptionPane.YES_OPTION){
            String ID,name,IC,DOB,password,clear;

            clear = "";
            ID = (jTextFieldID.getText()).trim();
            IC = (jTextFieldIC.getText().trim());
            name = (jTextFieldName.getText().trim());
            DOB = (jTextFieldDOB.getText().trim());
            password = (jTextFieldaddPassword.getText().trim());

            if(ID.length()==0 || name.length()==0 || IC.length()==0 || DOB.length()==0 || password.length()==0){
                JOptionPane.showMessageDialog(null,"Form incomplete!");
            }else if(committee.checkDuplicateCommittee(IC)==true){
                JOptionPane.showMessageDialog(null,"ID or Name already exist! Please try again!");
            }else{
                committee.setName(name);
                committee.setDOB(DOB);
                committee.setPassword(password);
                name = committee.getName();
                DOB = committee.getDOB();
                password = committee.getPassword();
                Committee committee = new Committee();
                JOptionPane.showMessageDialog(null,committee.edit(ID,IC,name,DOB,password));
            }
            ViewCommittee();
            jTextFieldID.setText(clear);
            jTextFieldName.setText(clear);
            jTextFieldIC.setText(clear);
            jTextFieldDOB.setText(clear);
            jTextFieldaddPassword.setText(clear);
        }
    }//GEN-LAST:event_jButtonEditCommitteeActionPerformed

    private void jButtonDeleteCommitteeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteCommitteeActionPerformed
        int response = JOptionPane.showConfirmDialog(null, "Please Confitm to DELETE!", "Select Option", JOptionPane.YES_NO_OPTION);
        if (response == JOptionPane.YES_OPTION){
            ArrayList<String> peoplelist = new ArrayList<String>();
            peoplelist.clear();
            List<String> searchlist = new ArrayList<>();
            String ID;
            int id;
            ID = (jTextFieldID.getText()).trim();
            id = Integer.parseInt(ID);
            committee.setID(id);
            if(ID.isEmpty()){
                JOptionPane.showMessageDialog(null,"Enter an ID to delete!");
            }
            else{
                JOptionPane.showMessageDialog(null,committee.deleteCommittee(committee.getID()));
            }
            ViewCommittee();
        }
    }//GEN-LAST:event_jButtonDeleteCommitteeActionPerformed

    private void jTextFieldSearchInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSearchInputActionPerformed
        List<String> psearchlist = new ArrayList<>();
        String searchID[];
        String line,ID;
        int id;
        ID = (jTextFieldSearchInput.getText()).trim();
        if(ID.isEmpty()){
            JOptionPane.showMessageDialog(null,"Enter an ID to delete!");
            ViewCommittee();
        }
        else{
            id = Integer.parseInt(ID);
            committee.setID(id);
            psearchlist = committee.searchCommittee(committee.getID());
            for (String element : psearchlist) {
                searchID = element.split(",");

                DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
                tblModel.setRowCount(0);
                tblModel.addRow(searchID);

            }
        }
    }//GEN-LAST:event_jTextFieldSearchInputActionPerformed

    private void jTextFieldDOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDOBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update_Committee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update_Committee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update_Committee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update_Committee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update_Committee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonDeleteCommittee;
    private javax.swing.JButton jButtonEditCommittee;
    private javax.swing.JButton jButtonaddCommittee;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelHomeMenuBar;
    private javax.swing.JLabel jLabelLogoutMenuBar;
    private javax.swing.JLabel jLabelUpdateAppointmentMenuBar;
    private javax.swing.JLabel jLabelUpdateCommitteeMenuBar;
    private javax.swing.JLabel jLabelUpdatePeopleMenuBar;
    private javax.swing.JLabel jLabelUpdateVaccineMenuBar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldDOB;
    private javax.swing.JTextField jTextFieldIC;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldSearchInput;
    private javax.swing.JTextField jTextFieldaddPassword;
    // End of variables declaration//GEN-END:variables
}
