/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import Classes.Committee;
import Classes.Centre;
import Classes.Vaccine;


import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Writer;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JUN WEI
 */
public class UpdateVaccine extends javax.swing.JFrame {

    /**
     * Creates new form UpdateVaccine
     */
    public UpdateVaccine() {
        initComponents();
        ViewVaccine();
    }
    Committee committee = new Committee();
    Vaccine vaccine = new Vaccine();
    Centre Centre = new Centre();
    
    public void ViewVaccine(){
       String vaccine[]; 
       List<String> vaccinelist = new ArrayList<>(); 
       String line = ""; 
       DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
       tblModel.setRowCount(0);//Reset jTable, Clear all data
       
        vaccinelist = committee.ViewVaccine();
        for (String element : vaccinelist) {
            vaccine = element.split(",");
               
            tblModel.addRow(vaccine);

            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelUpdateVaccineMenuBar = new javax.swing.JLabel();
        jLabelHomeMenuBar = new javax.swing.JLabel();
        jLabelUpdatePeopleMenuBar = new javax.swing.JLabel();
        jLabelLogoutMenuBar = new javax.swing.JLabel();
        jLabelUpdateCommitteetMenuBar = new javax.swing.JLabel();
        jLabelUpdateAppointmentMenuBar1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldVacID = new javax.swing.JTextField();
        jTextFieldvacQuantity = new javax.swing.JTextField();
        jButtonClearVac = new javax.swing.JButton();
        jButtonAddVac = new javax.swing.JButton();
        jButtonEditVac = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jButtonDeleteVac = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxVaccineCentre = new javax.swing.JComboBox<>();
        jTextFieldSearchVac = new javax.swing.JTextField();
        jComboBoxVaccine = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        jLabelUpdateVaccineMenuBar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelUpdateVaccineMenuBar.setText("Update Vaccine");
        jLabelUpdateVaccineMenuBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelUpdateVaccineMenuBarMouseClicked(evt);
            }
        });

        jLabelHomeMenuBar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelHomeMenuBar.setText("Home");
        jLabelHomeMenuBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHomeMenuBarMouseClicked(evt);
            }
        });

        jLabelUpdatePeopleMenuBar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelUpdatePeopleMenuBar.setText("Update People");
        jLabelUpdatePeopleMenuBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelUpdatePeopleMenuBarMouseClicked(evt);
            }
        });

        jLabelLogoutMenuBar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelLogoutMenuBar.setText("Logout");
        jLabelLogoutMenuBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLogoutMenuBarMouseClicked(evt);
            }
        });

        jLabelUpdateCommitteetMenuBar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelUpdateCommitteetMenuBar.setText("Update Committee");
        jLabelUpdateCommitteetMenuBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelUpdateCommitteetMenuBarMouseClicked(evt);
            }
        });

        jLabelUpdateAppointmentMenuBar1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelUpdateAppointmentMenuBar1.setText("Update Appointment");
        jLabelUpdateAppointmentMenuBar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelUpdateAppointmentMenuBar1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabelHomeMenuBar)
                .addGap(108, 108, 108)
                .addComponent(jLabelUpdatePeopleMenuBar)
                .addGap(103, 103, 103)
                .addComponent(jLabelUpdateVaccineMenuBar)
                .addGap(100, 100, 100)
                .addComponent(jLabelUpdateAppointmentMenuBar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(jLabelUpdateCommitteetMenuBar)
                .addGap(82, 82, 82)
                .addComponent(jLabelLogoutMenuBar)
                .addGap(41, 41, 41))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHomeMenuBar)
                    .addComponent(jLabelUpdatePeopleMenuBar)
                    .addComponent(jLabelUpdateVaccineMenuBar)
                    .addComponent(jLabelUpdateCommitteetMenuBar)
                    .addComponent(jLabelLogoutMenuBar)
                    .addComponent(jLabelUpdateAppointmentMenuBar1))
                .addGap(55, 55, 55))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel6.setText("Name:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel7.setText("ID:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel8.setText("Quantity:");

        jTextFieldVacID.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextFieldVacID.setToolTipText("");

        jTextFieldvacQuantity.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        jButtonClearVac.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonClearVac.setText("Clear");
        jButtonClearVac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearVacActionPerformed(evt);
            }
        });

        jButtonAddVac.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonAddVac.setText("Add");
        jButtonAddVac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddVacActionPerformed(evt);
            }
        });

        jButtonEditVac.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonEditVac.setText("Edit");
        jButtonEditVac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditVacActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Quantity", "Center"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable1.setRowHeight(25);
        jScrollPane1.setViewportView(jTable1);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel11.setText("Updating Vaccine");

        jButtonDeleteVac.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonDeleteVac.setText("Delete");
        jButtonDeleteVac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteVacActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel9.setText("Centre:");

        jComboBoxVaccineCentre.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jComboBoxVaccineCentre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Centre", "Kuala Lumpur", "Selangor", "Penang", "Sabah", "Sarawak", "Negeri Sembilan", "Malacca" }));
        jComboBoxVaccineCentre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxVaccineCentreActionPerformed(evt);
            }
        });

        jTextFieldSearchVac.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextFieldSearchVac.setText("Search ID");
        jTextFieldSearchVac.setToolTipText("Enter an ID to search");
        jTextFieldSearchVac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSearchVacActionPerformed(evt);
            }
        });

        jComboBoxVaccine.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jComboBoxVaccine.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Vaccine", "AstraZeneca", "Johnson&Johnson", "Pfizer" }));
        jComboBoxVaccine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxVaccineActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxVaccine, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxVaccineCentre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel6))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextFieldvacQuantity)
                            .addComponent(jTextFieldVacID, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(24, 24, 24))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonAddVac, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonClearVac)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonEditVac)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonDeleteVac))
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 958, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSearchVac, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSearchVac, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldVacID, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxVaccine, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jLabel8)
                        .addGap(1, 1, 1)
                        .addComponent(jTextFieldvacQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel9)
                        .addGap(1, 1, 1)
                        .addComponent(jComboBoxVaccineCentre, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAddVac)
                            .addComponent(jButtonClearVac)
                            .addComponent(jButtonEditVac)
                            .addComponent(jButtonDeleteVac)))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelUpdateVaccineMenuBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelUpdateVaccineMenuBarMouseClicked
        UpdateVaccine updatevac = new UpdateVaccine();
        updatevac.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabelUpdateVaccineMenuBarMouseClicked

    private void jLabelHomeMenuBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHomeMenuBarMouseClicked
        Personnel_Menu pm = new Personnel_Menu();
        pm.setVisible(true);
        dispose();

    }//GEN-LAST:event_jLabelHomeMenuBarMouseClicked

    private void jLabelUpdatePeopleMenuBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelUpdatePeopleMenuBarMouseClicked
        Update_People updatep = new Update_People();
        updatep.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabelUpdatePeopleMenuBarMouseClicked

    private void jLabelLogoutMenuBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLogoutMenuBarMouseClicked
        int response = JOptionPane.showConfirmDialog(null, "Please Confitm to LOGOUT!", "Select Option", JOptionPane.YES_NO_OPTION);
        if (response == JOptionPane.YES_OPTION){
            committee.logout();
            dispose();
        }
    }//GEN-LAST:event_jLabelLogoutMenuBarMouseClicked

    private void jLabelUpdateCommitteetMenuBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelUpdateCommitteetMenuBarMouseClicked
        Update_Committee updatecommit = new Update_Committee();
        updatecommit.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabelUpdateCommitteetMenuBarMouseClicked

    private void jLabelUpdateAppointmentMenuBar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelUpdateAppointmentMenuBar1MouseClicked
        UpdateAppointment updateapt = new UpdateAppointment();
        updateapt.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabelUpdateAppointmentMenuBar1MouseClicked

    private void jButtonClearVacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearVacActionPerformed
        int response = JOptionPane.showConfirmDialog(null, "Please Confitm to CLEAR!", "Select Option", JOptionPane.YES_NO_OPTION);
        if (response == JOptionPane.YES_OPTION){
            String clear = "";
            jTextFieldVacID.setText(clear);
            jComboBoxVaccine.setSelectedItem("Select Vaccine");
            jTextFieldvacQuantity.setText(clear);
            jComboBoxVaccineCentre.setSelectedItem("Select Centre");
        }
    }//GEN-LAST:event_jButtonClearVacActionPerformed

    private void jButtonAddVacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddVacActionPerformed
        int response = JOptionPane.showConfirmDialog(null, "Please Confitm to ADD!", "Select Option", JOptionPane.YES_NO_OPTION);
        if (response == JOptionPane.YES_OPTION){
            String vacID,vacName,vacQuantity, centre;
            String clear = "";
            Object vacCentre,VacName;

            vacID = (jTextFieldVacID.getText()).trim();
            VacName = jComboBoxVaccine.getSelectedItem();
            vacQuantity = (jTextFieldvacQuantity.getText()).trim();
            vacCentre = (jComboBoxVaccineCentre.getSelectedItem());

            vacName = VacName.toString();
            vaccine.setVacID(vacID);
            vaccine.setVacName(vacName);
            vaccine.setVacQuantity(vacQuantity);

            centre = vacCentre.toString();
            Centre.setCentre(centre);


            if(vacID.length()==0 || vacName=="Select Vaccine" || vacQuantity.length()==0 || centre=="Select Centre"){
                JOptionPane.showMessageDialog(null,"Form Incomplete!");
            }else if(committee.checkDuplicateVaccine(vacID, vacName, centre)==true){
                JOptionPane.showMessageDialog(null,"ID/Name/centre already exist! Please try again!");
            }else{
                JOptionPane.showMessageDialog(null,committee.addVaccine(vaccine.getVacID(),vaccine.getVacName(),vaccine.getVacQuantity(),Centre.getCentre()));
                jTextFieldVacID.setText(clear);
                jComboBoxVaccine.setSelectedItem("Select Vaccine");
                jTextFieldvacQuantity.setText(clear);
                jComboBoxVaccineCentre.setSelectedItem("Select Centre");
            }
            ViewVaccine();
        }
    }//GEN-LAST:event_jButtonAddVacActionPerformed

    private void jButtonEditVacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditVacActionPerformed
        int response = JOptionPane.showConfirmDialog(null, "Please Confitm to EDIT!", "Select Option", JOptionPane.YES_NO_OPTION);
        if (response == JOptionPane.YES_OPTION){
            String vacID,vacName,vacQuantity, centre;
            Object vacCenter,VacName;
            String clear = "";
            vacID = (jTextFieldVacID.getText()).trim();
            VacName = jComboBoxVaccine.getSelectedItem();
            vacQuantity = (jTextFieldvacQuantity.getText()).trim();
            vacCenter = (jComboBoxVaccineCentre.getSelectedItem());

            vacName = VacName.toString();
            vaccine.setVacID(vacID);
            vaccine.setVacName(vacName);
            vaccine.setVacQuantity(vacQuantity);

            centre = vacCenter.toString();
            Centre.setCentre(centre);

            if(vacID.length()==0 || vacName=="Select Vaccine" || vacQuantity.length()==0 || centre=="Select Center"){
                JOptionPane.showMessageDialog(null,"Form Incomplete!");
            }else if(committee.checkDuplicateVaccine(vaccine.getVacID(), vaccine.getVacName(), vaccine.getVacQuantity(),Centre.getCentre())==true){
                JOptionPane.showMessageDialog(null,"Vaccine Name at centre already exist! Please try again!");
            }
            else{
                JOptionPane.showMessageDialog(null,committee.edit(vaccine.getVacID(),vaccine.getVacName(),vaccine.getVacQuantity(),Centre.getCentre()));
                jTextFieldVacID.setText(clear);
                jComboBoxVaccine.setSelectedItem("Select Vaccine");
                jTextFieldvacQuantity.setText(clear);
                jComboBoxVaccineCentre.setSelectedItem("Select Centre");
            }
            ViewVaccine();
        }
    }//GEN-LAST:event_jButtonEditVacActionPerformed

    private void jButtonDeleteVacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteVacActionPerformed
        int response = JOptionPane.showConfirmDialog(null, "Please Confitm to DELETE!", "Select Option", JOptionPane.YES_NO_OPTION);
        if (response == JOptionPane.YES_OPTION){
            ArrayList<String> vaccinelist = new ArrayList<String>();
            vaccinelist.clear();
            String ID;
            ID = (jTextFieldVacID.getText()).trim();

            vaccine.setVacID(ID);

            if(ID.isEmpty()){
                JOptionPane.showMessageDialog(null,"Enter an ID to delete!");
            }
            else{
                JOptionPane.showMessageDialog(null,committee.deleteVaccine(vaccine.getVacID()));
            }
            ViewVaccine();
        }
    }//GEN-LAST:event_jButtonDeleteVacActionPerformed

    private void jComboBoxVaccineCentreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxVaccineCentreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxVaccineCentreActionPerformed

    private void jTextFieldSearchVacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSearchVacActionPerformed
        List<String> searchlist = new ArrayList<>();
        String searchID[];
        String line,ID;
        ID = (jTextFieldSearchVac.getText()).trim();
        vaccine.setVacID(ID);

        if(ID.isEmpty()){
            JOptionPane.showMessageDialog(null,"Enter an ID to delete!");
            ViewVaccine();
        }
        else{
            searchlist = committee.searchVaccine(vaccine.getVacID());
            for (String element : searchlist) {
                searchID = element.split(",");

                DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
                tblModel.setRowCount(0);
                tblModel.addRow(searchID);

            }
        }
    }//GEN-LAST:event_jTextFieldSearchVacActionPerformed

    private void jComboBoxVaccineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxVaccineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxVaccineActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateVaccine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateVaccine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateVaccine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateVaccine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateVaccine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddVac;
    private javax.swing.JButton jButtonClearVac;
    private javax.swing.JButton jButtonDeleteVac;
    private javax.swing.JButton jButtonEditVac;
    private javax.swing.JComboBox<String> jComboBoxVaccine;
    private javax.swing.JComboBox<String> jComboBoxVaccineCentre;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelHomeMenuBar;
    private javax.swing.JLabel jLabelLogoutMenuBar;
    private javax.swing.JLabel jLabelUpdateAppointmentMenuBar1;
    private javax.swing.JLabel jLabelUpdateCommitteetMenuBar;
    private javax.swing.JLabel jLabelUpdatePeopleMenuBar;
    private javax.swing.JLabel jLabelUpdateVaccineMenuBar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldSearchVac;
    private javax.swing.JTextField jTextFieldVacID;
    private javax.swing.JTextField jTextFieldvacQuantity;
    // End of variables declaration//GEN-END:variables
}
